from scapy.all import send
from scapy.layers.inet import UDP, IP
from scapy.contrib.rtps import (
    RTPS,
    ProtocolVersionPacket,
    VendorIdPacket,
    GUIDPrefixPacket,
    GUIDPacket,
    RTPSMessage,
    RTPSSubMessage_INFO_DST,
    RTPSSubMessage_INFO_TS,
    RTPSSubMessage_DATA,
    ParameterListPacket,
)
from scapy.contrib.rtps.rtps import DataPacket
from scapy.contrib.rtps.pid_types import (
    PID_TOPIC_NAME,
    PID_TYPE_NAME,
    PID_DURABILITY,
    PID_RELIABILITY,
    PID_PROTOCOL_VERSION,
    PID_VENDOR_ID,
    PID_ENDPOINT_GUID,
    PID_UNKNOWN,
    PID_SENTINEL,
    PID_DURABILITY_SERVICE,
    PID_LIFESPAN,
    PID_HISTORY,
    PID_USER_DATA,
)


def send_data_w_ros_discovery_info(ros2_node_ip, guid_prefix_packet):
    rtps_packet = RTPS(
        magic=b"RTPS",
        protocolVersion=ProtocolVersionPacket(major=2, minor=1),
        vendorId=VendorIdPacket(vendor_id=272),
        guidPrefix=GUIDPrefixPacket(
            hostId=17866087, appId=1130425663, instanceId=3681146987
        ),
    ) / RTPSMessage(
        submessages=[
            RTPSSubMessage_INFO_DST(
                submessageId=14,
                submessageFlags=1,
                octetsToNextHeader=12,
                guidPrefix=guid_prefix_packet,
            ),
            RTPSSubMessage_INFO_TS(
                submessageId=9,
                submessageFlags=1,
                octetsToNextHeader=8,
                ts_seconds=1730593610,
                ts_fraction=3507836882,
            ),
            RTPSSubMessage_DATA(
                submessageId=21,
                submessageFlags=5,
                octetsToNextHeader=192,
                extraFlags=0,
                octetsToInlineQoS=16,
                readerEntityIdKey=3,
                readerEntityIdKind=199,
                writerEntityIdKey=3,
                writerEntityIdKind=194,
                writerSeqNumHi=0,
                writerSeqNumLow=1,
                data=DataPacket(
                    encapsulationKind=3,
                    encapsulationOptions=0,
                    parameterList=ParameterListPacket(
                        parameterValues=[
                            PID_TOPIC_NAME(
                                parameterId=5,
                                parameterLength=24,
                                parameterData=b"\x13\x00\x00\x00ros_discovery_info\x00\x00",
                            ),
                            PID_TYPE_NAME(
                                parameterId=7,
                                parameterLength=56,
                                parameterData=b"4\x00\x00\x00rmw_dds_common::msg::dds_::ParticipantEntitiesInfo_\x00",
                            ),
                            PID_DURABILITY(
                                parameterId=29,
                                parameterLength=4,
                                parameterData=b"\x01\x00\x00\x00",
                            ),
                            PID_RELIABILITY(
                                parameterId=26,
                                parameterLength=12,
                                parameterData=b"\x02\x00\x00\x00\xff\xff\xff\x7f\xff\xff\xff\xff",
                            ),
                            PID_PROTOCOL_VERSION(
                                parameterId=21,
                                parameterLength=4,
                                protocolVersion=ProtocolVersionPacket(major=2, minor=1),
                                padding=b"\x00\x00",
                            ),
                            PID_VENDOR_ID(
                                parameterId=22,
                                parameterLength=4,
                                vendorId=VendorIdPacket(vendor_id=272),
                                padding=b"\x00\x00",
                            ),
                            PID_ENDPOINT_GUID(
                                parameterId=90,
                                parameterLength=16,
                                guid=GUIDPacket(
                                    hostId=17866087,
                                    appId=1130425663,
                                    instanceId=3681146987,
                                    entityId=1027,
                                ),
                            ),
                            PID_UNKNOWN(
                                parameterId=32780,
                                parameterLength=4,
                                parameterData=b"\x01\x00\x00\x00",
                            ),
                            PID_UNKNOWN(
                                parameterId=32771,
                                parameterLength=4,
                                parameterData=b"\x00\x00\x00\x00",
                            ),
                        ],
                        sentinel=PID_SENTINEL(
                            parameterId=1, parameterLength=0, parameterData=b""
                        ),
                    ),
                ),
            ),
            RTPSSubMessage_INFO_TS(
                submessageId=9,
                submessageFlags=1,
                octetsToNextHeader=8,
                ts_seconds=1730593610,
                ts_fraction=3518949535,
            ),
            RTPSSubMessage_DATA(
                submessageId=21,
                submessageFlags=5,
                octetsToNextHeader=220,
                extraFlags=0,
                octetsToInlineQoS=16,
                readerEntityIdKey=3,
                readerEntityIdKind=199,
                writerEntityIdKey=3,
                writerEntityIdKind=194,
                writerSeqNumHi=0,
                writerSeqNumLow=2,
                data=DataPacket(
                    encapsulationKind=3,
                    encapsulationOptions=0,
                    parameterList=ParameterListPacket(
                        parameterValues=[
                            PID_TOPIC_NAME(
                                parameterId=5,
                                parameterLength=16,
                                parameterData=b"\n\x00\x00\x00rt/rosout\x00\x00\x00",
                            ),
                            PID_TYPE_NAME(
                                parameterId=7,
                                parameterLength=36,
                                parameterData=b" \x00\x00\x00rcl_interfaces::msg::dds_::Log_\x00",
                            ),
                            PID_DURABILITY(
                                parameterId=29,
                                parameterLength=4,
                                parameterData=b"\x01\x00\x00\x00",
                            ),
                            PID_DURABILITY_SERVICE(
                                parameterId=30,
                                parameterLength=28,
                                parameterData=b"\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xe8\x03\x00\x00\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff",
                            ),
                            PID_RELIABILITY(
                                parameterId=26,
                                parameterLength=12,
                                parameterData=b"\x02\x00\x00\x00\xff\xff\xff\x7f\xff\xff\xff\xff",
                            ),
                            PID_LIFESPAN(
                                parameterId=43,
                                parameterLength=8,
                                parameterData=b"\n\x00\x00\x00\x00\x00\x00\x00",
                            ),
                            PID_HISTORY(
                                parameterId=64,
                                parameterLength=8,
                                parameterData=b"\x00\x00\x00\x00\xe8\x03\x00\x00",
                            ),
                            PID_PROTOCOL_VERSION(
                                parameterId=21,
                                parameterLength=4,
                                protocolVersion=ProtocolVersionPacket(major=2, minor=1),
                                padding=b"\x00\x00",
                            ),
                            PID_VENDOR_ID(
                                parameterId=22,
                                parameterLength=4,
                                vendorId=VendorIdPacket(vendor_id=272),
                                padding=b"\x00\x00",
                            ),
                            PID_ENDPOINT_GUID(
                                parameterId=90,
                                parameterLength=16,
                                guid=GUIDPacket(
                                    hostId=17866087,
                                    appId=1130425663,
                                    instanceId=3681146987,
                                    entityId=1539,
                                ),
                            ),
                            PID_UNKNOWN(
                                parameterId=32780,
                                parameterLength=4,
                                parameterData=b"\x01\x00\x00\x00",
                            ),
                            PID_UNKNOWN(
                                parameterId=32771,
                                parameterLength=4,
                                parameterData=b"\x00\x00\x00\x00",
                            ),
                        ],
                        sentinel=PID_SENTINEL(
                            parameterId=1, parameterLength=0, parameterData=b""
                        ),
                    ),
                ),
            ),
            RTPSSubMessage_INFO_TS(
                submessageId=9,
                submessageFlags=1,
                octetsToNextHeader=8,
                ts_seconds=1730593610,
                ts_fraction=3527003161,
            ),
            RTPSSubMessage_DATA(
                submessageId=21,
                submessageFlags=5,
                octetsToNextHeader=272,
                extraFlags=0,
                octetsToInlineQoS=16,
                readerEntityIdKey=3,
                readerEntityIdKind=199,
                writerEntityIdKey=3,
                writerEntityIdKind=194,
                writerSeqNumHi=0,
                writerSeqNumLow=3,
                data=DataPacket(
                    encapsulationKind=3,
                    encapsulationOptions=0,
                    parameterList=ParameterListPacket(
                        parameterValues=[
                            PID_USER_DATA(
                                parameterId=44,
                                parameterLength=60,
                                parameterData=b"6\x00\x00\x00serviceid= 1.10.9d.67.43.60.ed.3f.db.69.d8.6b.0.0.0.1;\x00\x00",
                            ),
                            PID_TOPIC_NAME(
                                parameterId=5,
                                parameterLength=36,
                                parameterData=b"\x1e\x00\x00\x00rr/talker/get_parametersReply\x00\x00\x00",
                            ),
                            PID_TYPE_NAME(
                                parameterId=7,
                                parameterLength=56,
                                parameterData=b"3\x00\x00\x00rcl_interfaces::srv::dds_::GetParameters_Response_\x00\x00",
                            ),
                            PID_RELIABILITY(
                                parameterId=26,
                                parameterLength=12,
                                parameterData=b"\x02\x00\x00\x00\xff\xff\xff\x7f\xff\xff\xff\xff",
                            ),
                            PID_HISTORY(
                                parameterId=64,
                                parameterLength=8,
                                parameterData=b"\x00\x00\x00\x00\xe8\x03\x00\x00",
                            ),
                            PID_PROTOCOL_VERSION(
                                parameterId=21,
                                parameterLength=4,
                                protocolVersion=ProtocolVersionPacket(major=2, minor=1),
                                padding=b"\x00\x00",
                            ),
                            PID_VENDOR_ID(
                                parameterId=22,
                                parameterLength=4,
                                vendorId=VendorIdPacket(vendor_id=272),
                                padding=b"\x00\x00",
                            ),
                            PID_ENDPOINT_GUID(
                                parameterId=90,
                                parameterLength=16,
                                guid=GUIDPacket(
                                    hostId=17866087,
                                    appId=1130425663,
                                    instanceId=3681146987,
                                    entityId=1795,
                                ),
                            ),
                            PID_UNKNOWN(
                                parameterId=32780,
                                parameterLength=4,
                                parameterData=b"\x01\x00\x00\x00",
                            ),
                            PID_UNKNOWN(
                                parameterId=32771,
                                parameterLength=4,
                                parameterData=b"\x00\x00\x00\x00",
                            ),
                        ],
                        sentinel=PID_SENTINEL(
                            parameterId=1, parameterLength=0, parameterData=b""
                        ),
                    ),
                ),
            ),
            RTPSSubMessage_INFO_TS(
                submessageId=9,
                submessageFlags=1,
                octetsToNextHeader=8,
                ts_seconds=1730593610,
                ts_fraction=3529610794,
            ),
            RTPSSubMessage_DATA(
                submessageId=21,
                submessageFlags=5,
                octetsToNextHeader=280,
                extraFlags=0,
                octetsToInlineQoS=16,
                readerEntityIdKey=3,
                readerEntityIdKind=199,
                writerEntityIdKey=3,
                writerEntityIdKind=194,
                writerSeqNumHi=0,
                writerSeqNumLow=4,
                data=DataPacket(
                    encapsulationKind=3,
                    encapsulationOptions=0,
                    parameterList=ParameterListPacket(
                        parameterValues=[
                            PID_USER_DATA(
                                parameterId=44,
                                parameterLength=60,
                                parameterData=b"6\x00\x00\x00serviceid= 1.10.9d.67.43.60.ed.3f.db.69.d8.6b.0.0.0.2;\x00\x00",
                            ),
                            PID_TOPIC_NAME(
                                parameterId=5,
                                parameterLength=40,
                                parameterData=b"#\x00\x00\x00rr/talker/get_parameter_typesReply\x00\x00",
                            ),
                            PID_TYPE_NAME(
                                parameterId=7,
                                parameterLength=60,
                                parameterData=b"7\x00\x00\x00rcl_interfaces::srv::dds_::GetParameterTypes_Response_\x00\x00",
                            ),
                            PID_RELIABILITY(
                                parameterId=26,
                                parameterLength=12,
                                parameterData=b"\x02\x00\x00\x00\xff\xff\xff\x7f\xff\xff\xff\xff",
                            ),
                            PID_HISTORY(
                                parameterId=64,
                                parameterLength=8,
                                parameterData=b"\x00\x00\x00\x00\xe8\x03\x00\x00",
                            ),
                            PID_PROTOCOL_VERSION(
                                parameterId=21,
                                parameterLength=4,
                                protocolVersion=ProtocolVersionPacket(major=2, minor=1),
                                padding=b"\x00\x00",
                            ),
                            PID_VENDOR_ID(
                                parameterId=22,
                                parameterLength=4,
                                vendorId=VendorIdPacket(vendor_id=272),
                                padding=b"\x00\x00",
                            ),
                            PID_ENDPOINT_GUID(
                                parameterId=90,
                                parameterLength=16,
                                guid=GUIDPacket(
                                    hostId=17866087,
                                    appId=1130425663,
                                    instanceId=3681146987,
                                    entityId=2307,
                                ),
                            ),
                            PID_UNKNOWN(
                                parameterId=32780,
                                parameterLength=4,
                                parameterData=b"\x01\x00\x00\x00",
                            ),
                            PID_UNKNOWN(
                                parameterId=32771,
                                parameterLength=4,
                                parameterData=b"\x00\x00\x00\x00",
                            ),
                        ],
                        sentinel=PID_SENTINEL(
                            parameterId=1, parameterLength=0, parameterData=b""
                        ),
                    ),
                ),
            ),
            RTPSSubMessage_INFO_TS(
                submessageId=9,
                submessageFlags=1,
                octetsToNextHeader=8,
                ts_seconds=1730593610,
                ts_fraction=3531244613,
            ),
            RTPSSubMessage_DATA(
                submessageId=21,
                submessageFlags=5,
                octetsToNextHeader=272,
                extraFlags=0,
                octetsToInlineQoS=16,
                readerEntityIdKey=3,
                readerEntityIdKind=199,
                writerEntityIdKey=3,
                writerEntityIdKind=194,
                writerSeqNumHi=0,
                writerSeqNumLow=5,
                data=DataPacket(
                    encapsulationKind=3,
                    encapsulationOptions=0,
                    parameterList=ParameterListPacket(
                        parameterValues=[
                            PID_USER_DATA(
                                parameterId=44,
                                parameterLength=60,
                                parameterData=b"6\x00\x00\x00serviceid= 1.10.9d.67.43.60.ed.3f.db.69.d8.6b.0.0.0.3;\x00\x00",
                            ),
                            PID_TOPIC_NAME(
                                parameterId=5,
                                parameterLength=36,
                                parameterData=b"\x1e\x00\x00\x00rr/talker/set_parametersReply\x00\x00\x00",
                            ),
                            PID_TYPE_NAME(
                                parameterId=7,
                                parameterLength=56,
                                parameterData=b"3\x00\x00\x00rcl_interfaces::srv::dds_::SetParameters_Response_\x00\x00",
                            ),
                            PID_RELIABILITY(
                                parameterId=26,
                                parameterLength=12,
                                parameterData=b"\x02\x00\x00\x00\xff\xff\xff\x7f\xff\xff\xff\xff",
                            ),
                            PID_HISTORY(
                                parameterId=64,
                                parameterLength=8,
                                parameterData=b"\x00\x00\x00\x00\xe8\x03\x00\x00",
                            ),
                            PID_PROTOCOL_VERSION(
                                parameterId=21,
                                parameterLength=4,
                                protocolVersion=ProtocolVersionPacket(major=2, minor=1),
                                padding=b"\x00\x00",
                            ),
                            PID_VENDOR_ID(
                                parameterId=22,
                                parameterLength=4,
                                vendorId=VendorIdPacket(vendor_id=272),
                                padding=b"\x00\x00",
                            ),
                            PID_ENDPOINT_GUID(
                                parameterId=90,
                                parameterLength=16,
                                guid=GUIDPacket(
                                    hostId=17866087,
                                    appId=1130425663,
                                    instanceId=3681146987,
                                    entityId=2819,
                                ),
                            ),
                            PID_UNKNOWN(
                                parameterId=32780,
                                parameterLength=4,
                                parameterData=b"\x01\x00\x00\x00",
                            ),
                            PID_UNKNOWN(
                                parameterId=32771,
                                parameterLength=4,
                                parameterData=b"\x00\x00\x00\x00",
                            ),
                        ],
                        sentinel=PID_SENTINEL(
                            parameterId=1, parameterLength=0, parameterData=b""
                        ),
                    ),
                ),
            ),
        ]
    )

    udp_packet = UDP(sport=33653, dport=7410)
    ip_packet = IP(dst=ros2_node_ip)

    packet = ip_packet / udp_packet / rtps_packet
    send(packet)
